core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', upload_file_view, name='upload-view'),
    path('data', get_data, name='get_data'),
    path('download-csv', d_csv, name='d_csv'),
]

task/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('', include('task1.urls', namespace='task1')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task1/urls.py
from django.urls import path
from .views import *

app_name = 'task1'

urlpatterns = [
    path('task1', task, name='task'),
]

core/models.py
from django.db import models
from django.utils.translation import activate


class Csv(models.Model):
    file_name = models.FileField(upload_to='core')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)


class Data(models.Model):
    date = models.CharField(max_length=200)
    appl_open = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    appl_high = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    appl_low = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    appl_close = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    appl_volume = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    appl_adjusted = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    dn = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    mavg = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    up = models.DecimalField(max_digits=100, decimal_places=5, blank=True, null=True)
    direction = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    

task1/models.py
from django.db import models


class Football(models.Model):
    player_name = models.CharField(max_length=200)
    player_type = models.CharField(max_length=200)
    date_created = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.player_name + ' ' + self.player_type


class Cricket(models.Model):
    player_name = models.CharField(max_length=200)
    player_type = models.CharField(max_length=200)
    date_created = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.player_name + ' ' + self.player_type

core/forms.py
from django import forms
from .models import *


class CsvModelForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name', )

core/views.py
from django.shortcuts import render
from django.utils.translation import activate
from .forms import CsvModelForm
from .models import Csv, Data
import csv
from .utils import get_plot, get_boxplot, get_histogram
import numpy as np
import matplotlib.pyplot as plt
from django.http import HttpResponse, response
from django.core.paginator import EmptyPage, Paginator
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from datetime import datetime
from django.db import transaction


@transaction.atomic
def upload_file_view(request):
    start_time = datetime.now()
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)
            for i, row in enumerate(reader):
                if i == 0:
                    pass
                else:
                    date = row[0]
                    appl_open = row[1]
                    appl_high = row[2]
                    appl_low = row[3]
                    appl_close = row[4]
                    appl_volume = row[5]
                    appl_adjusted = row[6]
                    dn = row[7]
                    mavg = row[8]
                    up = row[9]
                    direction = row[10]

                    Data.objects.bulk_create([
                        Data (
                            date = date, appl_open = appl_open, appl_high = appl_high, appl_low = appl_low,
                            appl_close = appl_close, appl_volume = appl_volume, appl_adjusted = appl_adjusted,
                            dn = dn, mavg = mavg, up = up, direction = direction 
                            )                   
                    ])
                   
            obj.activated = True
            obj.save()
            end_time = datetime.now()
            print('Duration: {}'.format(end_time - start_time))

    return render(request, 'core/task.html', {'form' : form})



def get_data(request):
    dataset = Data.objects.all()
    qs = Data.objects.get_queryset().order_by('id')
    x = [x.appl_low for x in dataset]
    y = [y.appl_high for y in dataset]
    z = [z.appl_open for z in dataset]
    w = [w.appl_close for w in dataset]
    v = [v.appl_volume for v in dataset]
    area = 14
    colors = np.random.rand(len(x))
    chart = get_plot(z, w, area, colors)
    data_1 = np.random.normal(x)
    data_2 = np.random.normal(y)
    data_3 = np.random.normal(z)
    data_4 = np.random.normal(w)
    data_5 = np.random.normal(v)
    data = [data_1, data_2, data_3, data_4]
    chart2 = get_boxplot(data)
    chart3 = get_histogram(data_5)
    p = Paginator(qs, 5)
    page_num = request.GET.get('page', 1)

    try :
        page = p.page(page_num)
    except EmptyPage:
        page = p.page(1)

    return render(request, 'core/table.html', {'dataset': dataset, 'qs': page, 'chart': chart, 'chart2': chart2, 'chart3': chart3})


def d_csv(request):
    dataset = Data.objects.all()
    response = HttpResponse(content_type = 'text/csv')
    response['Content-Disposition'] = 'attachment; filename=data.csv'
    writer = csv.writer(response)

    writer.writerow(['Date', 'aapl_open', 'appl_high', 'appl_low', 'appl_close', 'appl_volume', 'appl_adjusted', 'dn', 'mavg', 'up', 'direction'])

    for data in dataset:
        writer.writerow([data.date, data.appl_open, data.appl_high, data.appl_low, data.appl_close, data.appl_volume, data.appl_adjusted, data.dn, data.mavg, data.up, data.direction ])
    return response


task1/views.py
from django.shortcuts import render
from .models import *
from itertools import chain
from operator import attrgetter
from django.http import HttpResponse


def task(request):
    footballdata = Football.objects.all()
    cricketdata = Cricket.objects.all()
    football = list(footballdata)
    cricket = list(cricketdata)
    result = list(football) + list(cricket)
    result_data = footballdata.union(cricketdata, all=True)
    
    merged_list = sorted(   
        chain(footballdata, cricketdata),
        key=attrgetter('date_created'))

    return render(request, 'task1/task1.html', {'merged_list' : merged_list, 'footballdata' : footballdata, 'cricketdata' : cricketdata, 'result' : result, 'result_data' : result_data})

core/templates/core/table.html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Show Data</title>
  </head>
  <body>
  <script type="text/javascript">
        $("#btnPrint").live("click", function () {
            var divContents = $("#dvContainer").html();
            var printWindow = window.open('', '', 'height=400,width=800');
            printWindow.document.write('<html><head><title>DIV Contents</title>');
            printWindow.document.write('</head><body >');
            printWindow.document.write(divContents);
            printWindow.document.write('</body></html>');
            printWindow.document.close();
            printWindow.print();
        });
    </script>

    <script>

    $( document ).ready(function() {
    $('#lnkPrint').click(function()
     {
         window.print();
     });
});
    </script>

    <style>
      a:hover {
        background-color: rgba(75, 75, 74, 0.548);
    }
  </style>

    <nav class="navbar fixed-top navbar-dark bg-dark">
      <a class="navbar-brand active" href="/">Upload CSV</a>
      <a class="navbar-brand" href="task1">Check Task 01</a>
      <a class="navbar-brand" href="data">Explore Data</a>
      <a class="navbar-brand" style="float:right;" href="{% url 'core:d_csv' %}"> Download CSV File</a>
      <a class="navbar-brand" href="#" id="lnkPrint">Print HTML</a>
      <input style="float:right;" type="button" value="Download PDF File" id="btnPrint" />
      
    </nav>
    <br>
    <br>
  
  <style>
table, th, td{
  border:1px solid black;
}
</style>
<!-- <a href="/" class="btn btn-outline-dark" role="button" aria-pressed="true"><i class="bi bi-house"></i> Go to Home</a> -->
<center>
    <h4 style="color:green"><u><b> Data Table </b><u/></h4>
</center>
  <a style="float:right;" href="{% url 'core:d_csv' %}" class="btn btn-outline-dark" role="button" aria-pressed="true"> Download CSV File</a>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Index</th>
      <th scope="col">Date</th>
      <th scope="col">AAPL Open</th>
      <th scope="col">AAPL High</th>
      <th scope="col">AAPL Low</th>
      <th scope="col">AAPL Close</th>
      <th scope="col">AAPL Volume</th>
      <th scope="col">AAPL Adjusted</th>
      <th scope="col">DN</th>
      <th scope="col">MAVG</th>
      <th scope="col">UP</th>
      <th scope="col">Direction</th>
    </tr>
  </thead>
    {% for q in qs %}
  <tbody>
    <tr>
      <th scope="row">{{q.id}}</th>
      <td>{{q.date}}</td>
      <td>{{q.appl_open}}</td> 
      <td>{{q.appl_high}}</td>
      <td>{{q.appl_low}}</td>
      <td>{{q.appl_close}}</td>
      <td>{{q.appl_volume}}</td>
      <td>{{q.appl_adjusted}}</td>
      <td>{{q.dn}}</td>
      <td>{{q.mavg}}</td>
      <td>{{q.up}}</td>
      <td>{{q.direction}}</td>
    </tr>
  </tbody>

 {% endfor %}
</table>
 <div style="float:right;">
 {% if qs.has_previous %}
  <a href="{% url 'core:get_data' %}?page={{qs.previous_page_number}}"> <<< Previous Data</a>
  {% endif %}
    {% if qs.has_next %}
  <a href="{% url 'core:get_data' %}?page={{qs.next_page_number}}">Next Data >>></a>
  {% endif %}
  </div>
<br>
<br>
<center>

<input style="float:right;" type="button" value="Download PDF File" id="btnPrint" />
 <form id="form1">
    <div id="dvContainer">    
<div class="tabset">
  <input type="radio" name="tabset" id="tab1" aria-controls="marzen" checked>
  <label for="tab1"> Histogram ChartJS</label>
  <input type="radio" name="tabset" id="tab2" aria-controls="rauchbier">
  <label for="tab2">Scatter Plot</label>
  <input type="radio" name="tabset" id="tab3" aria-controls="dunkles">
  <label for="tab3">Histogram Matplot</label>
  <input type="radio" name="tabset" id="tab4" aria-controls="histogram">
  <label for="tab4">Box Plot</label>
    
  <div class="tab-panels">
    <section id="marzen" class="tab-panel">
      <div class="chartBox">
  <canvas id="histogram"></canvas>
</div>
  </section>
    <section id="rauchbier" class="tab-panel">
      <div>
{% if chart %}
    <img src="data:image/png;base64, {{ chart|safe }}"
    {% endif %}
</div>
    </section>

    <section id="histogram" class="tab-panel">
      <div>
{% if chart3 %}
    <img src="data:image/png;base64, {{ chart3|safe }}"
    {% endif %}
</div>
    </section>
    <section id="dunkles" class="tab-panel">
     <div>
{% if chart2 %}
    <img src="data:image/png;base64, {{ chart2|safe }}"
    {% endif %}
</div>
    </section>
  </div>
  
</div>
    

</center>



<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        <style>

            /*
            CSS for the main interaction
            */
            .tabset > input[type="radio"] {
            position: absolute;
            left: -200vw;
            }

            .tabset .tab-panel {
            display: none;
            }

            .tabset > input:first-child:checked ~ .tab-panels > .tab-panel:first-child,
            .tabset > input:nth-child(3):checked ~ .tab-panels > .tab-panel:nth-child(2),
            .tabset > input:nth-child(5):checked ~ .tab-panels > .tab-panel:nth-child(3),
            .tabset > input:nth-child(7):checked ~ .tab-panels > .tab-panel:nth-child(4),
            .tabset > input:nth-child(9):checked ~ .tab-panels > .tab-panel:nth-child(5),
            .tabset > input:nth-child(11):checked ~ .tab-panels > .tab-panel:nth-child(6) {
            display: block;
            }

            /*
            Styling
            */
            body {
            font: 16px/1.5em "Overpass", "Open Sans", Helvetica, sans-serif;
            color: #333;
            font-weight: 300;
            }

            .tabset > label {
            position: relative;
            display: inline-block;
            padding: 15px 15px 25px;
            border: 1px solid transparent;
            border-bottom: 0;
            cursor: pointer;
            font-weight: 600;
            }

            .tabset > label::after {
            content: "";
            position: absolute;
            left: 15px;
            bottom: 10px;
            width: 22px;
            height: 4px;
            background: #8d8d8d;
            }

            .tabset > label:hover,
            .tabset > input:focus + label {
            color: #06c;
            }

            .tabset > label:hover::after,
            .tabset > input:focus + label::after,
            .tabset > input:checked + label::after {
            background: #06c;
            }

            .tabset > input:checked + label {
            border-color: #ccc;
            border-bottom: 1px solid #fff;
            margin-bottom: -1px;
            }

            .tab-panel {
            padding: 30px 0;
            border-top: 1px solid #ccc;
            }

            /*
            Demo purposes only
            */
            *,
            *:before,
            *:after {
            box-sizing: border-box;
            }

            body {
            padding: 30px;
            }

            .tabset {
            max-width: 65em;
            }

            .chartBox {
                width: 900px;
                height: 500px;
            }

            </style>

            <script>
            const ctx = document.getElementById('histogram').getContext('2d');

            const chart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for data in dataset %} {{ data.id }}, {% endfor %}],
                datasets: [{
                label: 'AAPL High vs AAPL High Index',
                data: [{% for data in dataset %} {{ data.appl_high }}, {% endfor %}],
                backgroundColor: 'green',
                borderWidth: 0,
                barPercentage: 1,
                categoryPercentage: 1
                }]
            },
            options: {
                scales: {
                xAxes: [{
                    display: false,
                    barPercentage: 1,
                    ticks: {
                    max: 3,
                    }

                }, {
                    display: true,
                    ticks: {
                    autoSkip: false,
                    max: 4,
                    }
                }],
                yAxes: [{
                   
                    ticks: {
                    beginAtZero: true,
                    }
                }]
                }
            }
            });

            </script> 


</div>
    
    </form>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

core/templates/core/task.html
{% extends 'base.html' %} 

{% block title %}
2
{% endblock title %}

{% block content %}
<br>
<br>
<nav class="navbar fixed-top navbar-dark bg-dark">
    
    <a class="navbar-brand" href="/">Upload CSV</a>
    <a class="navbar-brand" href="data">Explore Data</a>
    <a class="navbar-brand" href="task1">Check Task 01</a>

  </nav>


  <br>
  <br>
  <br>
  <br>

<form action="" method="POST" id="form" class="ui form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <br>
    <br>
    <button type="submit" class="ui secondary button"><i class="cloud icon"></i> Upload</button>
</form>
<br>
<br>
<br>
<br>
<center>
<button class="ui right labeled icon button">
  <i class="right arrow icon"></i>
  <a href="data">Show Data
</button>
</center>
{% comment %} 
<script>

    const form = document.getElementById('form')
    form.addEventListener("submit", submitHandler)

    function submitHandler(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: window.location.pathname,
            data: $("#form").serializer(),
            contentType:false,
            mimeType: 'multipart/form-data',
            dataType: 'json',
            success: function(data) {
                if (data.msg == 'Success'){
                    alert('Form is Submitted');
                }
            }
        })
    }

</script> {% endcomment %}




{% endblock content %}

task1/templates/task1/task1.html
<!doctype html>
<html lang="en">
  <head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Show Data</title>
  </head>
  <body>
  <nav class="navbar fixed-top navbar-dark bg-dark">
    
    <a class="navbar-brand" href="/">Upload CSV</a>
    <a class="navbar-brand" href="data">Explore Data</a>
    <a class="navbar-brand" href="task1">Check Task 01</a>

  </nav>
<center>


<br>
<br>
  <br>
  <h2><b><u>Task 01 Example</u></b></h2>
  <br>
  <br>
  <div>For the first quesryset, <br><br>{{footballdata}}</div> 
  <br>
  <br>
  <div>For the second quesryset, <br><br>{{cricketdata}}</div>
  <br>
  <br>
  <strong>Merging Quesryset in 3 Ways (Different Model Quesryset)</strong>
  <br>
  <br>
  <div>After Merging both quesryset using chain, <br><br>{{merged_list}}</div>
  <br>
  <br>
  <div>After Merging both quesryset using union, <br><br>{{result_data}}</div>
  <br>
  <br>
  <div>Turn Quesryset to List and Merge, <br><br>{{result}}</div> 
</center>

<style>
div {
  width: 1120px;
  padding: 10px;
  border: 5px solid gray;
  margin: 0;
}
</style>

  </body>
  </html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <title>Task - {% block title %}{% endblock title %}</title>

  </head>
  <body>
    <div class="ui container">
      
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>